esphome:
  name: "plantmonitor-1"
  friendly_name: plantmonitor-1
  platformio_options:
    board_build.f_cpu: 160000000L

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: #KEY

ota:
  password: #PWD

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wifitest Fallback Hotspot"
    password: "DJzLXMtRlbTJ"

captive_portal:

web_server:
    port: 80

light:
  - platform: binary
    name: "Blue Light"
    output: light_output
    id: led_light
    restore_mode: ALWAYS_OFF

output:
  - platform: gpio
    pin: GPIO2
    id: light_output
    inverted: true

sensor:
- platform: adc
  pin: A0
  id: "adcMoistureRaw"
  accuracy_decimals: 5
  name: "Plant - Moisture Level and Raw Sensor Data"
  update_interval: 30s
  filters:
    - calibrate_linear:
      - 0.29  -> 100.0
      - 0.62 -> 0
  unit_of_measurement: '%'
  device_class: voltage
  state_class: measurement
  raw: False
